name = "foodnager"
compatibility_date = "2024-12-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

# KV namespace dla sesji (wymagane przez @astrojs/cloudflare)
[[kv_namespaces]]
binding = "SESSION"
id = "5de27ec6fcf541939516db5ac820212f"

[env.production]
name = "foodnager"

[env.preview]
name = "foodnager-preview"
